# CouchDB-øvelser

### GetAllDatabases
GET http://{{user}}:{{password}}@{{host}}/_all_dbs

### LoginAndCreateSession
POST /_session
Host: {{host}}
Accept: application/json
Content-Type: application/json

{
    "name": "{{user}}",
    "password": "{{password}}"
}

### CreateDatabase
PUT {{baseUrl}}/kardemommeby

### GetDatabase
GET /kardemommeby/
Host: {{host}}

### PostDocument
POST /kardemommeby
Host: {{host}}
Content-Type: application/json

{
    "navn": "Kasper",
    "yrke": "Røver",
    "eiendeler": [
        "løve"
    ],
    "alder" : 25,
    "bosted" : "Røverhuset"
}

### CreateDocumentsInBulk
POST /kardemommeby/_bulk_docs
Host: {{host}}
Content-Type: application/json

{
   "docs": [
      {
         "navn": "Kasper",
         "yrke": "Røver",
         "eiendeler": [
            "løve"
         ],
         "alder": 25,
         "bosted": "Røverhuset"
      },
       {
         "navn": "Jesper",
         "yrke": "Røver",
         "eiendeler": [
            "løve"
         ],
         "alder": 27,
         "bosted": "Røverhuset"
      }, {
         "navn": "Jonatan",
         "yrke": "Røver",
         "eiendeler": [
            "løve"
         ],
         "alder": 25,
         "bosted": "Røverhuset"
      },
      {
         "navn": "Tobias",
         "alder": 70,
         "bosted": "Tårnet"
      },
      {
         "navn": "Syvertsen",
         "alder": 35,
         "yrke": "Trikkefører"
      },
      {
         "navn": "Sørensen",
         "alder": 55,
         "yrke": "Barberer"
      },
      {
         "navn": "Sofie",
         "alder": 29
      },
      {
         "navn": "Kamomille",
         "alder": 10,
         "tante": "Sofie",
         "eiendeler": [ "piano" ]
      },
      {
         "navn": "Bastian",
         "yrke": "Politimester"
      }
   ]
}

### GetAllDocuments
GET /kardemommeby/_all_docs
Host: {{host}}

### GetSpecificDocument

# Erstatt verdiene for id og rev med de som er generert av databasen i filen http-client.env.json

GET /kardemommeby/{{id}}
Host: {{host}}

### UpdateDocument
PUT /kardemommeby/{{id}}
Host: {{host}}
Content-Type: application/json

{
    "_rev": "{{rev}}",
    "navn": "Kasper",
    "yrke": "Røver",
    "eiendeler": [
    "løve",
    "tante Sofie"
    ],
    "alder": 26,
    "bosted": "Røverhuset"
}


### FindDocument
POST /kardemommeby/_find
Host: {{host}}
Content-Type: application/json

{
    "selector": {
        "yrke": { "$eq": "Røver" },
        "alder": { "$gt": 18 }
    },
    "fields": [ "_id", "_rev", "navn" ]
}

### CreateIndex
POST /kardemommeby/_index
Host: {{host}}
Content-Type: application/json

{
    "index": {
        "fields": [ "navn", "yrke", "alder" ]
    },
    "name": "person-index"
}
